### ISSUE TITLE
Please support iOS 15.1.1

### ISSUE THREAD

**Issue by IMCHO** [filsv/iPhoneOSDeviceSupport#107]

**Comment by awadeyar** [comment]
Please add iOS 15.1.1

**Comment by hongfeiyang** [comment]
Xcode is too dumb to download the correct iOS 15.1.1 support files

**Comment by Brad19** [comment]
Yep. i've added 15.1 simulator to Xcode, but it is not recognising at all. Need it badly. Any thoughts will be appreciated

**Comment by jonno85** [comment]
the renaming of the folder worked for me @Brad19, check the sub answers https://stackoverflow.com/questions/69303638/xcode-doesn-t-support-ios-15-0/69311146#comment124126728_69311146

**Comment by filsv** [comment]
@IMCHO Hi, please try to use this [iOS 15.2 Support files](https://github.com/filsv/iPhoneOSDeviceSupport/blob/master/15.2.zip).

**Comment by Brad19** [comment]
@jonno85 
- Sorry could not reply back at the earliest as I was working on a work around for the release and found that the issue we faced may not be related to 15.1 and we were trying to capture the error rather than crashing.

- But i tried renaming as you mentioned, but no luck. My xCode now is updated to 13.2 after os update to monterey.  in xCode 13.2, I could see 15.0 besides 15.2 simulator in xCode preferences. So i'm lil unsure what should i do now.
 
> the renaming of the folder worked for me @Brad19, check the sub answers https://stackoverflow.com/questions/69303638/xcode-doesn-t-support-ios-15-0/69311146#comment124126728_69311146
